services:
  - type: web
    name: liya-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - fromDatabase:
          name: liya-mongo
          property: connectionString
    autoDeploy: false
